### ISSUE TITLE
After CICD pipeline, commit and push the updated OML descriptions using owlSave and git

### ISSUE THREAD

**Issue by UTNAK** [UTNAK/kepler16b-using-imce-vocabulary#30]
## Checklist before submitting a feature request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

In #29 , we build a capability of analysis executions using CI/CD pipeline.
The next step is to update analysis results into oml description files.

## Describe the desired feature

- Add  ./gradlew owlSave task to analysis.yml
- Add tasks that commit and push updated oml files to the repo.

We need to be careful about how we manage the branch.

## Additional context

[Any additional context]

**Comment by pogi7** [comment]
@UTNAK What makes the most sense to me is to commit and push to a new branch and open a new PR.
We can do all of these tasks with Github Actions

Github Actions:
1. [Commit and Push](https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457)
2. [Make Pull Request](https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action)
