### ISSUE TITLE
Execute Simulation Code on a CICD Pipeline

### ISSUE THREAD

**Issue by pogi7** [UTNAK/kepler16b-using-imce-vocabulary#7]
## Checklist before submitting a feature request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

I would like to execute the simulation code in #6 on a CICD Pipeline.  I want the CICD pipeline to have at least 3 stages
1. Build / Simulation
2. Test
3. Deploy

## Describe the desired feature

I would like to execute the simulation code in #6 on a CICD Pipeline in order to see how simulations affect OML descriptions

## Additional context

[Any additional context]

**Comment by pogi7** [comment]
@UTNAK 
How to run CICD pipeline in GitHub Actions
1. Config CICD pipeline to follow requirements in Dev Container
2. Run on command line `quarto render src/analysis/analysisShell.qmd`
3. Deploy to Github Pages using a bot

**Comment by UTNAK** [comment]
When I use r2u as an image for R, following errors happened.

```
> library(devtools); install_github('UTNAK/tansakusuR')
Loading required package: usethis
Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
  Rate limit remaining: 59/60
  Rate limit reset at: 2024-05-24 20:22:30 UTC
```  
 
This might be related to the error in [here](https://forum.posit.co/t/github-action-failing-to-install-from-devtools/112325/4)

Now i am trying to use [https://github.com/r-lib/pak](https://github.com/r-lib/pak)

**Comment by UTNAK** [comment]
I found the `quarto -V` command works when the command run in the build job.

Same thing happened for `python -m nbconvert --output="analysis" --output-dir='.' --execute --to html src/analysis/analysisShell.ipynb --no-input`.

In the current analysis.yml file, separating the job of building the environment from the job of executing commands results in an error that the command does not exist.


<img width="952" alt="image" src="https://github.com/UTNAK/kepler16b-using-imce-vocabulary/assets/29029659/7ce48797-d06d-4b79-9175-79e4cc8f803b">
